plugins:
  # https://github.com/jest-community/eslint-plugin-jest
  - jest

env:
  es2021: true
  node: true

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

overrides: []

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules: {
'import/extensions': 'off',
'no-console': 'on',
'no-underscore-dangle: [2, { 'allow': ['__filename', '__dirname'] }]'
}
